services:
  db:
   platform: linux/x86_64
   image: postgres
   restart: always
   environment:
    POSTGRES_USER: postgres
    POSTGRES_DB: opencloak
    POSTGRES_PASSWORD: 12345678
   ports:
   - '5432:5432'
   volumes: 
   - ./postgres-data:/var/lib/postgresql
